## Parameter Definition
parameters:
- name: webappName
  type: string
  default: WebAppName
parameters:
- name: packageName
  type: string
  default: PackageName
  
#To tigger from master branch of Azure git repo
trigger:
- master

# From default pool
pool:
  name: 'default'

variables:
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreCLI@4
  inputs:
    command: 'build'
    arguments: '--configuration $(buildConfiguration)'
  displayName: 'dotnet build $(packageName)'


- task: DotNetCoreCLI@3
  inputs:
    command: publish
    publishWebProjects: True
    arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)'
    zipAfterPublish: True

# this code takes all the files in $(Build.ArtifactStagingDirectory) and uploads them as an artifact of your build.
- task: PublishPipelineArtifact@2
  inputs:
    targetPath: '$(Build.ArtifactStagingDirectory)' 
    artifactName: '$(webappName)'
# Deploying 
- task: DotNetCoreCLI@1
  inputs:
    command: publish
    publishWebProjects: True
    arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)'
    zipAfterPublish: True
